### ISSUE TITLE
feat(options): inverse of the file_types key in the setup (disable_file_types)

### ISSUE THREAD

**Issue by IndianBoy42** [tzachar/local-highlight.nvim#10]
Currently we can only choose every filetype or some manually defined set of filetypes. I think more commonly we would want [every filetype - a manually defined set of exclusions]

**Comment by tzachar** [comment]
You can implement this yourself, check out the [API](https://github.com/tzachar/local-highlight.nvim#api).
Just leave the `file_types` config option as `{}`, and use the `attach` interface to your liking.

**Comment by IndianBoy42** [comment]
Would you accept a PR adding this feature? you're right, I don't think its too hard to implement

**Comment by tzachar** [comment]
Sure

**Comment by tzachar** [comment]
closed by #11
