### ISSUE TITLE
Plugin is not attached to the buffer with the default config

### ISSUE THREAD

**Issue by MomePP** [tzachar/local-highlight.nvim#14]
Hi, by default config `M.config.file_types` has been set to `{}`
https://github.com/tzachar/local-highlight.nvim/blob/2bc873a7cd7f7402e4840c1807c66b9e3d069209/lua/local-highlight.lua#L9

by checking for `nil` value of this line
https://github.com/tzachar/local-highlight.nvim/blob/2bc873a7cd7f7402e4840c1807c66b9e3d069209/lua/local-highlight.lua#L224
this condition causes the evaluation to skip creating an autocmd to attach the buffer

i can solve it by changing this line to `next(M.config.file_types) == nil`

Edit: Created PR https://github.com/tzachar/local-highlight.nvim/pull/15

**Comment by tzachar** [comment]
This is by design.
check https://github.com/tzachar/local-highlight.nvim#file_types-and-disable_file_types
if `config.file_types` is `{}`, we do not attach to any buffer.

I think it would be better if the default was 'nil'.
Maybe change you PR?

**Comment by MomePP** [comment]
Yes, changing the default values would be better. I've updated the PR. 😃

Note: I also changed both `M.config.file_types` and `M.config.disable_file_types` to `nil` by default.

**Comment by MomePP** [comment]
This issue is solved by PR https://github.com/tzachar/local-highlight.nvim/pull/15
