### ISSUE TITLE
Minimum number of occurrences to highlight

### ISSUE THREAD

**Issue by rootex-** [tzachar/local-highlight.nvim#19]
Hi, thanks for your effort, 
Right now there is no way to prevent highlighting in cases when there is only 1 occurrence. 
Minimum number of occurrences to highlight would be a nice to have feature.

**Comment by tzachar** [comment]
You can disable the highlight of the word under the cursor.
Would achieve the same thing.

**Comment by rootex-** [comment]
Ok, thanks, that would be certainly enough for this use case.
