### ISSUE TITLE
[Feature] Some suggestions

### ISSUE THREAD

**Issue by pidgeon777** [tzachar/local-highlight.nvim#2]
First of all, thanks for this plugin.

These are some options it would be great to add because it seems that as of now, there are no other plugins offering these features:

- Enable word highlight in all buffers (e.g. `quickfix`), not just certain file types.

- Customize highlight colour for the current word.

- Define custom keywords to always highlight, with highlight groups. For example:

```lua
{
  keywords = {
    { "TODO",  "Todo" },
    { "ERROR", "Error" },
    { "FIXME", "Error" },
    { "NOTE",  "Comment" },
  },
}
```

and custom highlight groups, for example:

```lua
{
  highlight = {
    Todo    = { gui = "bold,italic", guifg = "Red" },
    Error   = { gui = "bold,italic", guifg = "Orange" },
    Comment = { gui = "bold,italic", guifg = "Grey" },
  },
}
```

also, it would be great to let the user define the custom keywords as regex patterns if needed.

**Comment by pidgeon777** [comment]
As for highlighting in every visible buffer, no matter the file type, it's possible with the following plugin, so maybe you could take a cue from here:

https://github.com/t9md/vim-quickhl

**Comment by tzachar** [comment]
I have added documentations on how to use the plugin's `attach` mechanism to create autocommands as you need.

As for the rest of your suggestions, they look cool, and PRs are more than welcome :-)
