### ISSUE TITLE
4 second highlight/de-highlight delay

### ISSUE THREAD

**Issue by smprather** [tzachar/local-highlight.nvim#20]
Any idea why I'm seeing a 4 second highlight delay? I checked the source to see if I could find a config for the delay for debounce, etc, but I didn't see anything. It also takes 4 seconds to de-highlight. I'm 99% sure this delay is synthetic, but I can't find the source. I commented all of my Lazy packages except yours (mason also commented, so no lsps running). Still 4 second delay.

- WSL on windows (vmmem 100%-CPU bug not in action). Everything else "snappy".
- Editing my small init.lua file. 277 lines.
- nvim 0.9.2
- Tmux if that matters

```lua
    {
        'tzachar/local-highlight.nvim',
        config = function()
            require('local-highlight').setup({
                file_types = {'python', 'cpp', 'lua'}, -- If this is given only attach to this
                -- OR attach to every filetype except:
                disable_file_types = {'tex'},
                hlgroup = 'Search',
                cw_hlgroup = nil,
                -- Whether to display highlights in INSERT mode or not
                insert_mode = false
            })
        end
    }
```

:LocalHighlightStat
Total Usage Count    : 2
Average Running Time : 0.210606 msec

tzachar/local-highlight.nvim
neovim/nvim-lspconfig
lukas-reineke/indent-blankline.nvim
nvim-treesitter/nvim-treesitte
hrsh7th/nvim-cm
numToStr/Comment.nvim
nvim-telescope/telescope.nvi

![image](https://github.com/tzachar/local-highlight.nvim/assets/6503931/621e9f0b-645d-4beb-b3b5-c5373b4feb98)

![image](https://github.com/tzachar/local-highlight.nvim/assets/6503931/409aabe4-a9ab-4de7-9753-37d73af9ee05)

Thanks!

**Comment by tzachar** [comment]
look at [https://github.com/tzachar/local-highlight.nvim?tab=readme-ov-file#how-the-plugin-works](the doc)

I suggest you change the `updatetime` value to something smaller.
