### ISSUE TITLE
How to disable the plugin per default?

### ISSUE THREAD

**Issue by ThomasD13** [tzachar/local-highlight.nvim#23]
Hi,
I couldnt find a solution for this yet: How can I start neovim with this plugin loaded but disabled?
If I want to use it, I would like to execute the user command "LocalHighlightToggle" explicitly. 

I tried it via 
`config = function()
require('local-highlight').setup({
default = false,
})`

but it did not work. 
I'm not sure if I miss something obvious here.

**Comment by tzachar** [comment]
Right now, there is no strait forward way of achieving this.
A workaround is to set config.filetype to something which will not match any filetype: `{xxx}`

**Comment by ThomasD13** [comment]
@tzachar Thank you very much for the workaround. This fixes it for me.
