### ISSUE TITLE
Highlight not work on line with comment

### ISSUE THREAD

**Issue by thiago-figueredo** [tzachar/local-highlight.nvim#25]
I'm using the default configuration. When i highlight `travelers` in the commented line the matches does not get highlighted, only if i uncomment the line. 

Actual behavior

![1](https://github.com/tzachar/local-highlight.nvim/assets/74860544/9d7ef029-b65f-4308-a1b1-2ab27518264f)

Expected to work in commented line

![2](https://github.com/tzachar/local-highlight.nvim/assets/74860544/633ead04-7469-44c3-862e-91f238efcd59)

**Comment by tzachar** [comment]
Can you provide a minimal complete example which I can download?

**Comment by thiago-figueredo** [comment]
Do you want my neovim config or the project ?

This is my neovim config folder:

[my-nvim.zip](https://github.com/tzachar/local-highlight.nvim/files/15095191/my-nvim.zip)

You can try replicate it in the `init.lua` file. Apparently it does not work with comments using `//`, `--`. I don't know it there are others.

![3](https://github.com/tzachar/local-highlight.nvim/assets/74860544/8b5ad4f7-5546-4257-b537-344364dcc30a)

![4](https://github.com/tzachar/local-highlight.nvim/assets/74860544/0f38caea-1df5-4262-9222-34a06d746ae4)

**Comment by tzachar** [comment]
Can you also provide the file with the problem?

**Comment by tzachar** [comment]
It works with comments for me.
Pls also check if you changed `iskeyword`

**Comment by thiago-figueredo** [comment]
I've found the problem. I was not using `require("local-highlight").setup()` in the `config`.

![6](https://github.com/tzachar/local-highlight.nvim/assets/74860544/12562994-3e5e-42c7-8199-78f00208f9ed)

Now it works. Thank you by your time and attention.
