### ISSUE TITLE
Add option to clear reference on CursorMoved and/or CursorMovedI

### ISSUE THREAD

**Issue by sonnybox** [tzachar/local-highlight.nvim#26]
Pretty self explanatory. I can start a pull request if you want. So far as a work around, I created a autocmd and call the preexisting clear function so it should be pretty easy to implement. You can set a boolean in the setup function.

```lua
vim.api.nvim_create_autocmd({ 'CursorMoved', 'CursorMovedI' }, {
	buffer = event.buf,
	callback = function()
		require('local-highlight').clear_usage_highlights(event.buf)
	end,
})
```

**Comment by sonnybox** [comment]
And just in case you're wondering where event comes from:
```lua
vim.api.nvim_create_autocmd('LspAttach', {
	callback = function(event)
	end
})
```

**Comment by tzachar** [comment]
First, you can just pass `0` as the buffer number, which means the current buffer.
Second, this probably makes the screen flicker a lot... I would personally find this annoying, but will favorably consider a PR.
