### ISSUE TITLE
Setting color scheme removes LocalHighlight

### ISSUE THREAD

**Issue by fredlebel** [tzachar/local-highlight.nvim#28]
At the end of my `init.lua` I call `vim.cmd.colorscheme(theme)`, this results in `local-highlight` no longer working.

Found this: https://www.reddit.com/r/neovim/comments/13u606c/nvim_set_hl_not_working_in_the_config_file/

And changing my config like this fixes the issue:
``` lua
return {
    "tzachar/local-highlight.nvim",
    config = function()
        local plugin = require("local-highlight")
        plugin.setup({
            hlgroup = "LocalHighlight",
            cw_hlgroup = "LocalHighlight",
        })

        ----------------------------------
        vim.api.nvim_create_autocmd("ColorScheme", {
            pattern = "*",
            callback = function()
                plugin.setup({
                    hlgroup = "LocalHighlight",
                    cw_hlgroup = "LocalHighlight",
                })
            end,
        })
        ----------------------------------
    end
}
```

Maybe this plugin should register its own autocmd?

edit: It's a tricky fix because I could have defined my own `LocalHighlight` which would get lost on `:colorscheme` and then changed back to default by the plugin.  Would `local-highlight` remember the custom highlight and restore it?

**Comment by tzachar** [comment]
I dont think this is related to your colorscheme.
What happens if you disable the `vim.cmd.colorscheme(theme)` altogether?

**Comment by fredlebel** [comment]
Then I don't have an issue.  This plugin works as expected.  The command `colorscheme` seems to completely delete the highlight group `LocalHighlight`.  I even check with `:Telescope highlights` and it's no longer listed.

Looking at other plugin repos, they do seem like they register `autocmd` to reapply their highlight groups:
- https://github.com/catgoose/nvim-colorizer.lua/blob/master/lua/colorizer.lua
- https://github.com/folke/todo-comments.nvim/blob/main/lua/todo-comments/highlight.lua
