### ISSUE TITLE
[Bug] No highlight because `TSDefinitionUsage` is a non-existent highlight

### ISSUE THREAD

**Issue by pidgeon777** [tzachar/local-highlight.nvim#3]
After installing the plugin, I found that here:

https://github.com/tzachar/local-highlight.nvim/blob/86ade9e4f2c6377efd31cc495f031c31d5ffef3f/lua/local-highlight.lua#L100

it is defined a highlight which is not existent in my setup, thus the plugin doesn't highlight any word.

I wonder where that highlight comes from, also it would be great to let the user configure the highlight by choosing something different (or by manually defining a new one with background, foreground, style etc.).

**Comment by smilovanovic** [comment]
Same problem here, I copied the source code locally and just used `CursorLine`. You should probably expose an option to override this value.

**Comment by smilovanovic** [comment]
Also, `updatetime` is 4000 by default which is too high, you should add to your readme some suggestion to set it to something more reasonable like 500.

**Comment by carbolymer** [comment]
@tzachar thanks for the fix. By the way, where does `TSDefinitionUsage` highlight come from?

**Comment by tzachar** [comment]
`TS` stands for treesitter.
It is the default highlight group for a definition when using treesitter.

**Comment by pidgeon777** [comment]
Strange, I'm missing that highlight, tested it on a `LUA` buffer with Treesitter on.

**Comment by vishalbalaji** [comment]
That highlight actually comes from the plugin <code>[nvim-treesitter-refactor](https://github.com/nvim-treesitter/nvim-treesitter-refactor/blob/master/plugin/nvim-treesitter-refactor.vim)</code>. From the looks of things, it just links to `Visual`. I would suggest that the docs be updated so that `hlgroup` is just `Visual`, it is a default vim/nvim highlight group.

**Comment by tzachar** [comment]
Good idea.
Ill change the default to Visual.

**Comment by tzachar** [comment]
@vishalbalaji 
last commit removes all references to TSDefinitions.
By default, the plugin now creates a highlight group for its usage, allowing the user to override it.

Cheers.

**Comment by vishalbalaji** [comment]
@tzachar That's great! Amazing work on the plugin, by the way :thumbsup:
