### ISSUE TITLE
Words in string should be excluded

### ISSUE THREAD

**Issue by Davidyz** [tzachar/local-highlight.nvim#5]
Currently the highlight included the same symbol in strings, which doesn't make sense to me. For example, the "vim" in the string `"shiracamus/vim-syntax-x86-objdump-d"` is not a lua symbol and should not have been highlighted. I believe treesitter is capable of avoiding this. 

![image](https://user-images.githubusercontent.com/30951234/218097026-c37be0c1-1b8a-4466-86da-cb546d625b84.png)

**Comment by tzachar** [comment]
This is exactly the point of this plugin.
*Not* to use treesitter, as using it to find out a word is not a proper node is very expensive.
