### ISSUE TITLE
can't make the plugin work

### ISSUE THREAD

**Issue by gilbh** [tzachar/local-highlight.nvim#7]
Love the idea!

I have placed the following in my _vimrc:
```
        'tzachar/local-highlight.nvim',
        config = function()
          require('local-highlight').setup({
              file_types = {'python'},
              hlgroup = 'TSDefinitionUsage',
          })
        end
    },
```

(I didn't copy the separate setup code from your README as it seems to duplicate the above).

Still nothing happens in my python file. I tried to verify activation by manually typing `:LocalHighlightOn` but still nothing happens. (BTW, all LocalHighlight* commands do not prompt the current status, might be helpful to add).

Anything that might indicate what the problem is? Or did I get something wrong in the install/use?

Thanks!

**Comment by tzachar** [comment]
Looks like your configuration structure is wrong. You are missing something at the start, probably a copy paste problem??

**Comment by gilbh** [comment]
That's totally my bad, here's the previous few lines:
```
  require('lazy').setup({
    {
        'tzachar/local-highlight.nvim',
        config = function()
          require('local-highlight').setup({
              file_types = {'python'},
              hlgroup = 'TSDefinitionUsage',
          })
        end
    },
.
.
.
.

 ```

Let me know if this makes sense now and whether I am doing something wrong. I could provide more specific info if relevant (like `checkhealth` perhaps? I am not the world champion in Vim, but I do love it very much!).

Thanks!!

**Comment by tzachar** [comment]
Can you try the latest version of the plugin?
Also, change you config as to match the README:
```lua
  require('lazy').setup({
    {
        'tzachar/local-highlight.nvim',
        config = function()
          require('local-highlight').setup({
              file_types = {'python'},
          })
        end
    }),
```

**Comment by gilbh** [comment]
Indeed, removing this line:
```
              hlgroup = 'TSDefinitionUsage',
```

-- did the trick! The plugin works now. 

I am not sure what the `hlgroup` stands for -- the README says it is "defined upon startup" by how exactly and so on -- maybe consider adding some explanation there. 

But in any case, thanks so much for your help. The plugin works now and it looks great!

**Comment by tzachar** [comment]
`hlgroup` is short hand for highlight group.
In this plugin's case, it is the highlight group used by the plugin to highlight the other occurrences oft the word  under the cursor.
